# Release Automation Workflow
name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0, v1.1.0, etc.
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-and-release:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build application
      run: npm run dist
      
    - name: Create release package
      run: |
        npm run release
        
    - name: Get version from tag
      id: get_version
      run: |
        $version = $env:GITHUB_REF -replace 'refs/tags/', ''
        echo "VERSION=$version" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
        
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        name: "iWood Slim Local App ${{ steps.get_version.outputs.VERSION }}"
        body: |
          ## iWood Slim Local Application - ${{ steps.get_version.outputs.VERSION }}
          
          ### 📦 What's Included
          - Standalone Windows executable (no Node.js required)
          - Complete web interface assets
          - Database setup scripts
          - Installation and deployment guides
          
          ### 🚀 Quick Start
          1. Download `iwood-slim-local-app-windows.zip`
          2. Extract to your desired folder
          3. Install MySQL 8.0+ 
          4. Run the SQL setup scripts
          5. Configure `.env` with your database credentials
          6. Double-click `start-iwood.bat` to launch
          7. Open http://localhost:3000 in your browser
          
          ### 📋 System Requirements
          - Windows 10/11 (64-bit)
          - MySQL 8.0+ or MariaDB 10.6+
          - 4GB+ RAM, 500MB storage
          
          See `INSTALLATION.md` for detailed setup instructions.
        files: |
          iwood-slim-local-app-windows.zip
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
